// Command gendirectencode regenerates EncodeDirect methods for every type in
// the root anthropic package that implements MarshalJSON.
//
// The DirectEncoder fast path (see internal/encoding/json) lets the encoder
// write a type's underlying value straight into the parent buffer, skipping the
// MarshalJSON -> Marshal -> []byte copy round-trip. Because the SDK's request
// and response types are generated by Stainless (and cannot be regenerated in
// this repo), this generator re-derives the EncodeDirect methods directly from
// the generated source so the fast path stays in sync after SDK upgrades.
//
// Classification (by the type's MarshalJSON body):
//   - param.MarshalObject  -> object fast path (return the method-stripped shadow)
//   - param.MarshalUnion   -> union fast path (return the single present member)
//   - anything else        -> safe fallback (return nil, false; encoder uses MarshalJSON)
//
// Run from the repository root:
//
//	go run ./internal/cmd/gendirectencode
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"sort"
	"strings"
)

type marshalKind int

const (
	kindOther marshalKind = iota
	kindObject
	kindUnion
)

type typeInfo struct {
	name    string
	kind    marshalKind
	members []unionMember // only for kindUnion
}

type unionMember struct {
	field   string
	pointer bool // true => check `!= nil`; false => check `.Valid()`
}

func main() {
	if err := run("."); err != nil {
		fmt.Fprintln(os.Stderr, "gendirectencode:", err)
		os.Exit(1)
	}
}

func run(dir string) error {
	fset := token.NewFileSet()
	entries, err := os.ReadDir(dir)
	if err != nil {
		return err
	}

	structs := map[string]*ast.StructType{}
	var marshalTypes []string
	marshalKinds := map[string]marshalKind{}

	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		src, err := os.ReadFile(name)
		if err != nil {
			return err
		}
		f, err := parser.ParseFile(fset, name, src, 0)
		if err != nil {
			return fmt.Errorf("parse %s: %w", name, err)
		}
		for _, decl := range f.Decls {
			switch d := decl.(type) {
			case *ast.GenDecl:
				for _, spec := range d.Specs {
					ts, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}
					if st, ok := ts.Type.(*ast.StructType); ok {
						structs[ts.Name.Name] = st
					}
				}
			case *ast.FuncDecl:
				if d.Recv == nil || len(d.Recv.List) == 0 || d.Name.Name != "MarshalJSON" {
					continue
				}
				typeName := receiverTypeName(d.Recv.List[0].Type)
				if typeName == "" {
					continue
				}
				body := string(src[fset.Position(d.Body.Pos()).Offset:fset.Position(d.Body.End()).Offset])
				// Only the canonical minimal MarshalJSON shapes are safe to
				// fast-path: object == `type shadow T; return param.MarshalObject(...)`
				// (2 statements) and union == `return param.MarshalUnion(...)`
				// (1 statement). Any MarshalJSON with extra logic (e.g. schema
				// conversion, MarshalWithExtras, custom marshalers) must keep its
				// MarshalJSON path, so it falls back.
				stmtCount := len(d.Body.List)
				kind := kindOther
				switch {
				case stmtCount == 2 && strings.Contains(body, "param.MarshalObject"):
					kind = kindObject
				case stmtCount == 1 && strings.Contains(body, "param.MarshalUnion"):
					kind = kindUnion
				}
				if _, seen := marshalKinds[typeName]; !seen {
					marshalTypes = append(marshalTypes, typeName)
				}
				marshalKinds[typeName] = kind
			}
		}
	}

	infos := make([]typeInfo, 0, len(marshalTypes))
	for _, name := range marshalTypes {
		ti := typeInfo{name: name, kind: marshalKinds[name]}
		if ti.kind == kindUnion {
			st := structs[name]
			if st == nil {
				// Union without a discoverable struct: fall back safely.
				ti.kind = kindOther
			} else {
				ti.members = unionMembers(st)
				if len(ti.members) == 0 {
					ti.kind = kindOther
				}
			}
		}
		infos = append(infos, ti)
	}
	sort.Slice(infos, func(i, j int) bool { return infos[i].name < infos[j].name })

	var buf bytes.Buffer
	buf.WriteString("// Code generated by internal/cmd/gendirectencode. DO NOT EDIT.\n\n")
	buf.WriteString("package anthropic\n\n")
	buf.WriteString("import \"github.com/anthropics/anthropic-sdk-go/packages/param\"\n\n")
	buf.WriteString("// EncodeDirect implements the json.DirectEncoder fast path. See the\n")
	buf.WriteString("// gendirectencode command and internal/encoding/json for details.\n\n")
	for _, ti := range infos {
		switch ti.kind {
		case kindObject:
			writeObject(&buf, ti.name)
		case kindUnion:
			writeUnion(&buf, ti.name, ti.members)
		default:
			writeFallback(&buf, ti.name)
		}
	}

	out, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format generated source: %w", err)
	}
	if err := os.WriteFile("directencode.go", out, 0o644); err != nil {
		return err
	}
	fmt.Printf("gendirectencode: wrote %d EncodeDirect methods\n", len(infos))
	return nil
}

func writeObject(buf *bytes.Buffer, name string) {
	fmt.Fprintf(buf, "func (r %s) EncodeDirect() (any, bool) {\n", name)
	buf.WriteString("\tif len(r.ExtraFields()) > 0 || param.IsNull(r) {\n\t\treturn nil, false\n\t}\n")
	buf.WriteString("\tif _, ok := r.Overrides(); ok {\n\t\treturn nil, false\n\t}\n")
	fmt.Fprintf(buf, "\ttype shadow %s\n", name)
	buf.WriteString("\treturn (*shadow)(&r), true\n}\n\n")
}

func writeUnion(buf *bytes.Buffer, name string, members []unionMember) {
	fmt.Fprintf(buf, "func (u %s) EncodeDirect() (any, bool) {\n", name)
	buf.WriteString("\tif param.IsNull(u) {\n\t\treturn nil, false\n\t}\n")
	buf.WriteString("\tif _, ok := u.Overrides(); ok {\n\t\treturn nil, false\n\t}\n")
	buf.WriteString("\tvar present any\n")
	for i, m := range members {
		// param.IsOmitted resolves presence uniformly for pointer, slice,
		// param.Opt, and constant members, mirroring the SDK's own asAny().
		fmt.Fprintf(buf, "\tif !param.IsOmitted(u.%s) {\n", m.field)
		if i > 0 {
			buf.WriteString("\t\tif present != nil {\n\t\t\treturn nil, false\n\t\t}\n")
		}
		// Pointer and slice members are already reference types; value
		// members (param.Opt, constant) are addressed so the encoder sees a
		// pointer, matching asAny().
		if m.pointer {
			fmt.Fprintf(buf, "\t\tpresent = u.%s\n\t}\n", m.field)
		} else {
			fmt.Fprintf(buf, "\t\tpresent = &u.%s\n\t}\n", m.field)
		}
	}
	buf.WriteString("\tif present == nil {\n\t\treturn nil, true\n\t}\n")
	buf.WriteString("\treturn present, true\n}\n\n")
}

func writeFallback(buf *bytes.Buffer, name string) {
	// Types whose MarshalJSON is neither a plain object nor a union (e.g.
	// MarshalWithExtras, custom marshalers) keep the standard MarshalJSON path.
	fmt.Fprintf(buf, "func (r %s) EncodeDirect() (any, bool) { return nil, false }\n\n", name)
}

// unionMembers returns the exported OfXxx fields of a union param struct in
// declaration order, classifying each as pointer/slice (nil check) or value
// (Valid check).
func unionMembers(st *ast.StructType) []unionMember {
	var members []unionMember
	for _, field := range st.Fields.List {
		for _, n := range field.Names {
			if !strings.HasPrefix(n.Name, "Of") || !n.IsExported() {
				continue
			}
			pointer := false
			switch field.Type.(type) {
			case *ast.StarExpr, *ast.ArrayType:
				pointer = true
			}
			members = append(members, unionMember{field: n.Name, pointer: pointer})
		}
	}
	return members
}

func receiverTypeName(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		if id, ok := t.X.(*ast.Ident); ok {
			return id.Name
		}
	case *ast.IndexExpr:
		if id, ok := t.X.(*ast.Ident); ok {
			return id.Name
		}
	}
	return ""
}
